// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Client.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.GRPc.Protos {

  /// <summary>Holder for reflection information generated from Proto/Client.proto</summary>
  public static partial class ClientReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Client.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90by9DbGllbnQucHJvdG8SB2NsaWVudHMiMgoRQ3JlYXRlVXNlclJl",
            "cXVlc3QSEAoIZnVsbE5hbWUYASABKAkSCwoDcm9sGAIgASgFInkKEUNyZWF0",
            "ZUNsaWVudFByb3RvEg4KBklkVHlwZRgBIAEoBRIQCghJZE51bWJlchgCIAEo",
            "CRINCgVOYW1lcxgDIAEoCRIRCglMYXN0TmFtZXMYBCABKAkSDQoFRW1haWwY",
            "BSABKAkSEQoJQmlydGhkYXRlGAYgASgJIjYKCVVzZXJQcm90bxIKCgJpZBgB",
            "IAEoCRIQCghmdWxsTmFtZRgCIAEoCRILCgNyb2wYAyABKAUimwIKC0NsaWVu",
            "dFByb3RvEhMKC0N1cnJlbnREYXRlGAEgASgJEgoKAklkGAIgASgJEg4KBklk",
            "VHlwZRgDIAEoBRIQCghJZE51bWJlchgEIAEoCRINCgVOYW1lcxgFIAEoCRIR",
            "CglMYXN0TmFtZXMYBiABKAkSDQoFRW1haWwYByABKAkSEQoJQmlydGhkYXRl",
            "GAggASgJEhQKDENyZWF0aW9uRGF0ZRgJIAEoCRIyCg5IaXN0b3J5VXBkYXRl",
            "cxgKIAMoCzIaLmNsaWVudHMuTW9kaWZpY2F0aW9uUHJvdG8SEQoJSXNFbmFi",
            "bGVkGAsgASgIEhYKDkhhc0FjdGl2ZURlYnRzGAwgASgIEhAKCFByb2R1Y3Rz",
            "GA0gAygJIgcKBUVtcHR5IjsKEkNsaWVudExpc3RSZXNwb25zZRIlCgdjbGll",
            "bnRzGAEgAygLMhQuY2xpZW50cy5DbGllbnRQcm90byJqChFNb2RpZmljYXRp",
            "b25Qcm90bxIYChBtb2RpZmljYXRpb25UeXBlGAEgASgFEiwKEG1vZGlmaWNh",
            "dGlvblVzZXIYAiABKAsyEi5jbGllbnRzLlVzZXJQcm90bxINCgVmZWNoYRgD",
            "IAEoCSJLChNDcmVhdGVDbGllbnRSZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoCRIk",
            "CgZjbGllbnQYAiABKAsyFC5jbGllbnRzLkNsaWVudFByb3RvMtEBCg5DbGll",
            "bnRTZXJ2aWNlcxI8CgpDcmVhdGVVc2VyEhouY2xpZW50cy5DcmVhdGVVc2Vy",
            "UmVxdWVzdBoSLmNsaWVudHMuVXNlclByb3RvEkIKDENyZWF0ZUNsaWVudBIc",
            "LmNsaWVudHMuQ3JlYXRlQ2xpZW50UmVxdWVzdBoULmNsaWVudHMuQ2xpZW50",
            "UHJvdG8SPQoORmluZEFsbENsaWVudHMSDi5jbGllbnRzLkVtcHR5GhsuY2xp",
            "ZW50cy5DbGllbnRMaXN0UmVzcG9uc2VCGqoCF0VudHJ5UG9pbnRzLkdSUGMu",
            "UHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CreateUserRequest), global::EntryPoints.GRPc.Protos.CreateUserRequest.Parser, new[]{ "FullName", "Rol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CreateClientProto), global::EntryPoints.GRPc.Protos.CreateClientProto.Parser, new[]{ "IdType", "IdNumber", "Names", "LastNames", "Email", "Birthdate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.UserProto), global::EntryPoints.GRPc.Protos.UserProto.Parser, new[]{ "Id", "FullName", "Rol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ClientProto), global::EntryPoints.GRPc.Protos.ClientProto.Parser, new[]{ "CurrentDate", "Id", "IdType", "IdNumber", "Names", "LastNames", "Email", "Birthdate", "CreationDate", "HistoryUpdates", "IsEnabled", "HasActiveDebts", "Products" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.Empty), global::EntryPoints.GRPc.Protos.Empty.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ClientListResponse), global::EntryPoints.GRPc.Protos.ClientListResponse.Parser, new[]{ "Clients" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ModificationProto), global::EntryPoints.GRPc.Protos.ModificationProto.Parser, new[]{ "ModificationType", "ModificationUser", "Fecha" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CreateClientRequest), global::EntryPoints.GRPc.Protos.CreateClientRequest.Parser, new[]{ "UserId", "Client" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Requests
  /// </summary>
  public sealed partial class CreateUserRequest : pb::IMessage<CreateUserRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateUserRequest> _parser = new pb::MessageParser<CreateUserRequest>(() => new CreateUserRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateUserRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateUserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateUserRequest(CreateUserRequest other) : this() {
      fullName_ = other.fullName_;
      rol_ = other.rol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateUserRequest Clone() {
      return new CreateUserRequest(this);
    }

    /// <summary>Field number for the "fullName" field.</summary>
    public const int FullNameFieldNumber = 1;
    private string fullName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rol" field.</summary>
    public const int RolFieldNumber = 2;
    private int rol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rol {
      get { return rol_; }
      set {
        rol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateUserRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateUserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FullName != other.FullName) return false;
      if (Rol != other.Rol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (Rol != 0) hash ^= Rol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FullName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FullName);
      }
      if (Rol != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FullName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FullName);
      }
      if (Rol != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (Rol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateUserRequest other) {
      if (other == null) {
        return;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.Rol != 0) {
        Rol = other.Rol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FullName = input.ReadString();
            break;
          }
          case 16: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FullName = input.ReadString();
            break;
          }
          case 16: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateClientProto : pb::IMessage<CreateClientProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateClientProto> _parser = new pb::MessageParser<CreateClientProto>(() => new CreateClientProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateClientProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientProto(CreateClientProto other) : this() {
      idType_ = other.idType_;
      idNumber_ = other.idNumber_;
      names_ = other.names_;
      lastNames_ = other.lastNames_;
      email_ = other.email_;
      birthdate_ = other.birthdate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientProto Clone() {
      return new CreateClientProto(this);
    }

    /// <summary>Field number for the "IdType" field.</summary>
    public const int IdTypeFieldNumber = 1;
    private int idType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IdType {
      get { return idType_; }
      set {
        idType_ = value;
      }
    }

    /// <summary>Field number for the "IdNumber" field.</summary>
    public const int IdNumberFieldNumber = 2;
    private string idNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdNumber {
      get { return idNumber_; }
      set {
        idNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Names" field.</summary>
    public const int NamesFieldNumber = 3;
    private string names_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Names {
      get { return names_; }
      set {
        names_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LastNames" field.</summary>
    public const int LastNamesFieldNumber = 4;
    private string lastNames_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastNames {
      get { return lastNames_; }
      set {
        lastNames_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Email" field.</summary>
    public const int EmailFieldNumber = 5;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Birthdate" field.</summary>
    public const int BirthdateFieldNumber = 6;
    private string birthdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Birthdate {
      get { return birthdate_; }
      set {
        birthdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateClientProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateClientProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdType != other.IdType) return false;
      if (IdNumber != other.IdNumber) return false;
      if (Names != other.Names) return false;
      if (LastNames != other.LastNames) return false;
      if (Email != other.Email) return false;
      if (Birthdate != other.Birthdate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdType != 0) hash ^= IdType.GetHashCode();
      if (IdNumber.Length != 0) hash ^= IdNumber.GetHashCode();
      if (Names.Length != 0) hash ^= Names.GetHashCode();
      if (LastNames.Length != 0) hash ^= LastNames.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Birthdate.Length != 0) hash ^= Birthdate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdType);
      }
      if (IdNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdNumber);
      }
      if (Names.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Names);
      }
      if (LastNames.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastNames);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Email);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Birthdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdType);
      }
      if (IdNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdNumber);
      }
      if (Names.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Names);
      }
      if (LastNames.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastNames);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Email);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Birthdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdType);
      }
      if (IdNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNumber);
      }
      if (Names.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Names);
      }
      if (LastNames.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastNames);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Birthdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Birthdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateClientProto other) {
      if (other == null) {
        return;
      }
      if (other.IdType != 0) {
        IdType = other.IdType;
      }
      if (other.IdNumber.Length != 0) {
        IdNumber = other.IdNumber;
      }
      if (other.Names.Length != 0) {
        Names = other.Names;
      }
      if (other.LastNames.Length != 0) {
        LastNames = other.LastNames;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Birthdate.Length != 0) {
        Birthdate = other.Birthdate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdType = input.ReadInt32();
            break;
          }
          case 18: {
            IdNumber = input.ReadString();
            break;
          }
          case 26: {
            Names = input.ReadString();
            break;
          }
          case 34: {
            LastNames = input.ReadString();
            break;
          }
          case 42: {
            Email = input.ReadString();
            break;
          }
          case 50: {
            Birthdate = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdType = input.ReadInt32();
            break;
          }
          case 18: {
            IdNumber = input.ReadString();
            break;
          }
          case 26: {
            Names = input.ReadString();
            break;
          }
          case 34: {
            LastNames = input.ReadString();
            break;
          }
          case 42: {
            Email = input.ReadString();
            break;
          }
          case 50: {
            Birthdate = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Responses
  /// </summary>
  public sealed partial class UserProto : pb::IMessage<UserProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserProto> _parser = new pb::MessageParser<UserProto>(() => new UserProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProto(UserProto other) : this() {
      id_ = other.id_;
      fullName_ = other.fullName_;
      rol_ = other.rol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProto Clone() {
      return new UserProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fullName" field.</summary>
    public const int FullNameFieldNumber = 2;
    private string fullName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rol" field.</summary>
    public const int RolFieldNumber = 3;
    private int rol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rol {
      get { return rol_; }
      set {
        rol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (FullName != other.FullName) return false;
      if (Rol != other.Rol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (Rol != 0) hash ^= Rol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (Rol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (Rol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (Rol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.Rol != 0) {
        Rol = other.Rol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 24: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 24: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ClientProto : pb::IMessage<ClientProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientProto> _parser = new pb::MessageParser<ClientProto>(() => new ClientProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientProto(ClientProto other) : this() {
      currentDate_ = other.currentDate_;
      id_ = other.id_;
      idType_ = other.idType_;
      idNumber_ = other.idNumber_;
      names_ = other.names_;
      lastNames_ = other.lastNames_;
      email_ = other.email_;
      birthdate_ = other.birthdate_;
      creationDate_ = other.creationDate_;
      historyUpdates_ = other.historyUpdates_.Clone();
      isEnabled_ = other.isEnabled_;
      hasActiveDebts_ = other.hasActiveDebts_;
      products_ = other.products_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientProto Clone() {
      return new ClientProto(this);
    }

    /// <summary>Field number for the "CurrentDate" field.</summary>
    public const int CurrentDateFieldNumber = 1;
    private string currentDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CurrentDate {
      get { return currentDate_; }
      set {
        currentDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdType" field.</summary>
    public const int IdTypeFieldNumber = 3;
    private int idType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IdType {
      get { return idType_; }
      set {
        idType_ = value;
      }
    }

    /// <summary>Field number for the "IdNumber" field.</summary>
    public const int IdNumberFieldNumber = 4;
    private string idNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdNumber {
      get { return idNumber_; }
      set {
        idNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Names" field.</summary>
    public const int NamesFieldNumber = 5;
    private string names_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Names {
      get { return names_; }
      set {
        names_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LastNames" field.</summary>
    public const int LastNamesFieldNumber = 6;
    private string lastNames_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastNames {
      get { return lastNames_; }
      set {
        lastNames_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Email" field.</summary>
    public const int EmailFieldNumber = 7;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Birthdate" field.</summary>
    public const int BirthdateFieldNumber = 8;
    private string birthdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Birthdate {
      get { return birthdate_; }
      set {
        birthdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreationDate" field.</summary>
    public const int CreationDateFieldNumber = 9;
    private string creationDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CreationDate {
      get { return creationDate_; }
      set {
        creationDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HistoryUpdates" field.</summary>
    public const int HistoryUpdatesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EntryPoints.GRPc.Protos.ModificationProto> _repeated_historyUpdates_codec
        = pb::FieldCodec.ForMessage(82, global::EntryPoints.GRPc.Protos.ModificationProto.Parser);
    private readonly pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ModificationProto> historyUpdates_ = new pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ModificationProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ModificationProto> HistoryUpdates {
      get { return historyUpdates_; }
    }

    /// <summary>Field number for the "IsEnabled" field.</summary>
    public const int IsEnabledFieldNumber = 11;
    private bool isEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsEnabled {
      get { return isEnabled_; }
      set {
        isEnabled_ = value;
      }
    }

    /// <summary>Field number for the "HasActiveDebts" field.</summary>
    public const int HasActiveDebtsFieldNumber = 12;
    private bool hasActiveDebts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasActiveDebts {
      get { return hasActiveDebts_; }
      set {
        hasActiveDebts_ = value;
      }
    }

    /// <summary>Field number for the "Products" field.</summary>
    public const int ProductsFieldNumber = 13;
    private static readonly pb::FieldCodec<string> _repeated_products_codec
        = pb::FieldCodec.ForString(106);
    private readonly pbc::RepeatedField<string> products_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Products {
      get { return products_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentDate != other.CurrentDate) return false;
      if (Id != other.Id) return false;
      if (IdType != other.IdType) return false;
      if (IdNumber != other.IdNumber) return false;
      if (Names != other.Names) return false;
      if (LastNames != other.LastNames) return false;
      if (Email != other.Email) return false;
      if (Birthdate != other.Birthdate) return false;
      if (CreationDate != other.CreationDate) return false;
      if(!historyUpdates_.Equals(other.historyUpdates_)) return false;
      if (IsEnabled != other.IsEnabled) return false;
      if (HasActiveDebts != other.HasActiveDebts) return false;
      if(!products_.Equals(other.products_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentDate.Length != 0) hash ^= CurrentDate.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (IdType != 0) hash ^= IdType.GetHashCode();
      if (IdNumber.Length != 0) hash ^= IdNumber.GetHashCode();
      if (Names.Length != 0) hash ^= Names.GetHashCode();
      if (LastNames.Length != 0) hash ^= LastNames.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Birthdate.Length != 0) hash ^= Birthdate.GetHashCode();
      if (CreationDate.Length != 0) hash ^= CreationDate.GetHashCode();
      hash ^= historyUpdates_.GetHashCode();
      if (IsEnabled != false) hash ^= IsEnabled.GetHashCode();
      if (HasActiveDebts != false) hash ^= HasActiveDebts.GetHashCode();
      hash ^= products_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurrentDate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CurrentDate);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (IdType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdType);
      }
      if (IdNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdNumber);
      }
      if (Names.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Names);
      }
      if (LastNames.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LastNames);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Email);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Birthdate);
      }
      if (CreationDate.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CreationDate);
      }
      historyUpdates_.WriteTo(output, _repeated_historyUpdates_codec);
      if (IsEnabled != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsEnabled);
      }
      if (HasActiveDebts != false) {
        output.WriteRawTag(96);
        output.WriteBool(HasActiveDebts);
      }
      products_.WriteTo(output, _repeated_products_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurrentDate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CurrentDate);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (IdType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdType);
      }
      if (IdNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdNumber);
      }
      if (Names.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Names);
      }
      if (LastNames.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LastNames);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Email);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Birthdate);
      }
      if (CreationDate.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CreationDate);
      }
      historyUpdates_.WriteTo(ref output, _repeated_historyUpdates_codec);
      if (IsEnabled != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsEnabled);
      }
      if (HasActiveDebts != false) {
        output.WriteRawTag(96);
        output.WriteBool(HasActiveDebts);
      }
      products_.WriteTo(ref output, _repeated_products_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CurrentDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentDate);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (IdType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdType);
      }
      if (IdNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNumber);
      }
      if (Names.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Names);
      }
      if (LastNames.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastNames);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Birthdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Birthdate);
      }
      if (CreationDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationDate);
      }
      size += historyUpdates_.CalculateSize(_repeated_historyUpdates_codec);
      if (IsEnabled != false) {
        size += 1 + 1;
      }
      if (HasActiveDebts != false) {
        size += 1 + 1;
      }
      size += products_.CalculateSize(_repeated_products_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientProto other) {
      if (other == null) {
        return;
      }
      if (other.CurrentDate.Length != 0) {
        CurrentDate = other.CurrentDate;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.IdType != 0) {
        IdType = other.IdType;
      }
      if (other.IdNumber.Length != 0) {
        IdNumber = other.IdNumber;
      }
      if (other.Names.Length != 0) {
        Names = other.Names;
      }
      if (other.LastNames.Length != 0) {
        LastNames = other.LastNames;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Birthdate.Length != 0) {
        Birthdate = other.Birthdate;
      }
      if (other.CreationDate.Length != 0) {
        CreationDate = other.CreationDate;
      }
      historyUpdates_.Add(other.historyUpdates_);
      if (other.IsEnabled != false) {
        IsEnabled = other.IsEnabled;
      }
      if (other.HasActiveDebts != false) {
        HasActiveDebts = other.HasActiveDebts;
      }
      products_.Add(other.products_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CurrentDate = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            IdType = input.ReadInt32();
            break;
          }
          case 34: {
            IdNumber = input.ReadString();
            break;
          }
          case 42: {
            Names = input.ReadString();
            break;
          }
          case 50: {
            LastNames = input.ReadString();
            break;
          }
          case 58: {
            Email = input.ReadString();
            break;
          }
          case 66: {
            Birthdate = input.ReadString();
            break;
          }
          case 74: {
            CreationDate = input.ReadString();
            break;
          }
          case 82: {
            historyUpdates_.AddEntriesFrom(input, _repeated_historyUpdates_codec);
            break;
          }
          case 88: {
            IsEnabled = input.ReadBool();
            break;
          }
          case 96: {
            HasActiveDebts = input.ReadBool();
            break;
          }
          case 106: {
            products_.AddEntriesFrom(input, _repeated_products_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CurrentDate = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            IdType = input.ReadInt32();
            break;
          }
          case 34: {
            IdNumber = input.ReadString();
            break;
          }
          case 42: {
            Names = input.ReadString();
            break;
          }
          case 50: {
            LastNames = input.ReadString();
            break;
          }
          case 58: {
            Email = input.ReadString();
            break;
          }
          case 66: {
            Birthdate = input.ReadString();
            break;
          }
          case 74: {
            CreationDate = input.ReadString();
            break;
          }
          case 82: {
            historyUpdates_.AddEntriesFrom(ref input, _repeated_historyUpdates_codec);
            break;
          }
          case 88: {
            IsEnabled = input.ReadBool();
            break;
          }
          case 96: {
            HasActiveDebts = input.ReadBool();
            break;
          }
          case 106: {
            products_.AddEntriesFrom(ref input, _repeated_products_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Empty : pb::IMessage<Empty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class ClientListResponse : pb::IMessage<ClientListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientListResponse> _parser = new pb::MessageParser<ClientListResponse>(() => new ClientListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientListResponse(ClientListResponse other) : this() {
      clients_ = other.clients_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientListResponse Clone() {
      return new ClientListResponse(this);
    }

    /// <summary>Field number for the "clients" field.</summary>
    public const int ClientsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EntryPoints.GRPc.Protos.ClientProto> _repeated_clients_codec
        = pb::FieldCodec.ForMessage(10, global::EntryPoints.GRPc.Protos.ClientProto.Parser);
    private readonly pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ClientProto> clients_ = new pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ClientProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ClientProto> Clients {
      get { return clients_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!clients_.Equals(other.clients_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= clients_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      clients_.WriteTo(output, _repeated_clients_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      clients_.WriteTo(ref output, _repeated_clients_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += clients_.CalculateSize(_repeated_clients_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientListResponse other) {
      if (other == null) {
        return;
      }
      clients_.Add(other.clients_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            clients_.AddEntriesFrom(input, _repeated_clients_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            clients_.AddEntriesFrom(ref input, _repeated_clients_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ModificationProto : pb::IMessage<ModificationProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ModificationProto> _parser = new pb::MessageParser<ModificationProto>(() => new ModificationProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModificationProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModificationProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModificationProto(ModificationProto other) : this() {
      modificationType_ = other.modificationType_;
      modificationUser_ = other.modificationUser_ != null ? other.modificationUser_.Clone() : null;
      fecha_ = other.fecha_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModificationProto Clone() {
      return new ModificationProto(this);
    }

    /// <summary>Field number for the "modificationType" field.</summary>
    public const int ModificationTypeFieldNumber = 1;
    private int modificationType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ModificationType {
      get { return modificationType_; }
      set {
        modificationType_ = value;
      }
    }

    /// <summary>Field number for the "modificationUser" field.</summary>
    public const int ModificationUserFieldNumber = 2;
    private global::EntryPoints.GRPc.Protos.UserProto modificationUser_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EntryPoints.GRPc.Protos.UserProto ModificationUser {
      get { return modificationUser_; }
      set {
        modificationUser_ = value;
      }
    }

    /// <summary>Field number for the "fecha" field.</summary>
    public const int FechaFieldNumber = 3;
    private string fecha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Fecha {
      get { return fecha_; }
      set {
        fecha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ModificationProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ModificationProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ModificationType != other.ModificationType) return false;
      if (!object.Equals(ModificationUser, other.ModificationUser)) return false;
      if (Fecha != other.Fecha) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ModificationType != 0) hash ^= ModificationType.GetHashCode();
      if (modificationUser_ != null) hash ^= ModificationUser.GetHashCode();
      if (Fecha.Length != 0) hash ^= Fecha.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ModificationType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ModificationType);
      }
      if (modificationUser_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ModificationUser);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ModificationType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ModificationType);
      }
      if (modificationUser_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ModificationUser);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ModificationType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ModificationType);
      }
      if (modificationUser_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModificationUser);
      }
      if (Fecha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Fecha);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ModificationProto other) {
      if (other == null) {
        return;
      }
      if (other.ModificationType != 0) {
        ModificationType = other.ModificationType;
      }
      if (other.modificationUser_ != null) {
        if (modificationUser_ == null) {
          ModificationUser = new global::EntryPoints.GRPc.Protos.UserProto();
        }
        ModificationUser.MergeFrom(other.ModificationUser);
      }
      if (other.Fecha.Length != 0) {
        Fecha = other.Fecha;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ModificationType = input.ReadInt32();
            break;
          }
          case 18: {
            if (modificationUser_ == null) {
              ModificationUser = new global::EntryPoints.GRPc.Protos.UserProto();
            }
            input.ReadMessage(ModificationUser);
            break;
          }
          case 26: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ModificationType = input.ReadInt32();
            break;
          }
          case 18: {
            if (modificationUser_ == null) {
              ModificationUser = new global::EntryPoints.GRPc.Protos.UserProto();
            }
            input.ReadMessage(ModificationUser);
            break;
          }
          case 26: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateClientRequest : pb::IMessage<CreateClientRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateClientRequest> _parser = new pb::MessageParser<CreateClientRequest>(() => new CreateClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClientReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientRequest(CreateClientRequest other) : this() {
      userId_ = other.userId_;
      client_ = other.client_ != null ? other.client_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateClientRequest Clone() {
      return new CreateClientRequest(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 2;
    private global::EntryPoints.GRPc.Protos.ClientProto client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EntryPoints.GRPc.Protos.ClientProto Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (!object.Equals(Client, other.Client)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (client_ != null) hash ^= Client.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (client_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Client);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (client_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Client);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::EntryPoints.GRPc.Protos.ClientProto();
        }
        Client.MergeFrom(other.Client);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            if (client_ == null) {
              Client = new global::EntryPoints.GRPc.Protos.ClientProto();
            }
            input.ReadMessage(Client);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            if (client_ == null) {
              Client = new global::EntryPoints.GRPc.Protos.ClientProto();
            }
            input.ReadMessage(Client);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
